FORMAT: 1A
HOST: http://chester.apiblueprint.org/

# chesster

Chesster is an API for playing chess, both with humans and computers.  
It also allows for chatting with other users.

## Users [/users]

### Search for users [GET]

+ Response 200 (application/json)

        [
            {'handle': 'RHowell'},
            {'handle': 'Mandelbrot'},
        ]

### Create a New User [POST]

Creates a new chess player user.  Defaults to a 1500 chess ranking.

+ Request (application/json)

        {
            "handle": "Sun Tzu",
            "email": "sun@tzu.com"
            "default_language": "zh-Hant-CN",
            "time_zone": "UTC-0500"
        }

+ Response 201 (application/json)
    + Headers

            Location: /users/2

    + Body

            {
                "handle": "Whitty Fella",
                "message": "Successfully created user \"Whitty Fella\""
                "created_at": "2015-12-14T18:40:51.620Z",
            }

+ Response 409 (application/json)
    + Body

            {
                "message": "A user with the email address \"sun@tzu.com\" already exists"
            }
