FORMAT: 1A
HOST: http://chester.apiblueprint.org/

# chesster

Chesster is an API for playing chess, both with humans and computers.  It also allows for chatting with other users.

## Users [/users/{?handle}]

### Search for users [GET]

+ Parameters
    + handle (string, optional) - The user handle to search for
    
+ Response 200 (application/json)

        [
            {'handle': 'RHowell'},
            {'handle': 'Mandelbrot'},
        ]

### Create a New User [POST]

+ Request (application/json)

        {
            "handle": "Sun Tzu",
            "email": "sun@tzu.com"
            "default_language": "zh-Hant-CN",
            "time_zone": "UTC-0500"
        }

+ Response 201 (application/json)
    + Headers

            Location: /users/2

    + Body

            {
                "handle": "Whitty Fella",
                "message": "Successfully created user \"Whitty Fella\""
                "created_at": "2015-12-14T18:40:51.620Z",
            }

+ Response 409 (application/json)
    + Body

            {
                "message": "A user with the email address \"sun@tzu.com\" already exists"
            }
            
### View User Profile [GET /users/{user_id}]

+ Parameters
    + user_id (number, required) - A users unique ID
    
+ Response 200 (application/json)

    + Body
    
            {
                "handle": "Sun Tzu",
                "email": "sun@tzu.com"
                "default_language": "zh-Hant-CN",
                "time_zone": "UTC-0500",
                "created_at": "2015-12-14T18:40:51.620Z",
                "elo_score": "1500"
            }

+ Response 404 (application/json)

    + Body
            
            {
                "message": "That user ID is not valid"
            }
            
+ Response 410 (application/json)

    + Body
    
            {
                "message": "That user account has been removed"
            }
            
### Update a user profile [PATCH /users/{user_id}]

+ Parameters
    + user_id (number, required) - A users unique ID
    
+ Request (application/json)

        {
            "default_language": "en-GB"    
        }
        
+ Response 200

+ Response 400 (application/json)

        { "message": "Explanation..." }
        
        

    
